#!python3
# -*- code by: utf-8 -*-
import unit.nayuki_core as nayuki_core


nayuki_core.run_command_from_yaml('execute', nayuki_core.MCDR_server_list_yaml_path, 'stop')
nayuki_core.run_command_from_yaml('execute', nayuki_core.minecraft_server_yaml_path, 'stop')